### ISSUE TITLE
Patient extensions to match OMOP

### ISSUE THREAD

**Issue by magic-lantern** [gt-health/GT-FHIR2#52]
It appears that this is the file that defines a patient in the GT-FHIR2 system:

GT-FHIR2/gt-fhir2-server/src/main/java/edu/gatech/chai/gtfhir2/mapping/OmopPatient.java

I'm interested in storing actual values for race and ethnicity. Currently the OmopPatient.java file has this block that assigns default values for race and ethnicity:

```java
                Concept race = new Concept();
                race.setId(8552L);
                fperson.setRaceConcept(race);

                // Ethnicity is not available in FHIR resource. Set to 0L as there is no
                // unknown ethnicity.
                Concept ethnicity = new Concept();
                ethnicity.setId(0L);
                fperson.setEthnicityConcept(ethnicity);
```

But these values cannot be set nor retrieved via the provided FHIR API.

The US Core Race extension (https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-race.html) and the US Core Ethnicity extension (https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-ethnicity.html) seem like a good fit for these items. 

Do you have an example of how to implement a custom profiles and extensions in GT-FHIR2?

**Comment by myungchoi** [comment]
We do have a plan to add those extensions. We recently decided to recreate DSTU2 from GT-FHIR2 (which is STU3). We will be adding Argonaut extension to this. 

For STU3, we will add USCore extension. 

These are on our roadmap.  The place for adding the extensions are in the edu.gatech.chai.gtfhir2.mode package. Currently, it has ArgoPatient.java file as a placeholder. This file name will be changed to USCorePatient for STU3 and ArgoPatient for DSTU2. These files are where we can put the extensions. 

I am about to push updates that rename all the packages to support an environment for both DSTU2 and STU3. Once this is done, USCorePatient.java can be used to add those extension. All related Omop mapping files also need to be supported.

I will update here once package rearrangement is done. When that happened, we should be able to work on the extensions. 

MyOrganization.java has a custom extension example.

**Comment by magic-lantern** [comment]
Thanks for the insight into your development plans as well as the general guidance on how to modify and add extensions. I look forward to your progress in this area!

**Comment by myungchoi** [comment]
Package rearrangement is done. Once we have DSTU2 completed (which will contain Patient extension for Argonaut profile), STU3 will also have those extensions (US Core profile).  Now, you should be able to see USCorePatient.java for a placeholder.

**Comment by myungchoi** [comment]
Extension for race and ethnicity is added as specified in US Core patient profile. Both read and write should work. Must use ombCategory for race and ethnicity codes.
