### ISSUE TITLE
Creating resources doesn't work

### ISSUE THREAD

**Issue by ckamann** [gt-health/GT-FHIR2#56]
Hey,

I set up an implementation of GT-FHIR2 with smart-postgresql in our Docker environment. After many struggles with the existing proxy, the database and the webserver are up and running. Now I encountered another problem when trying to create FHIR resources via the WebInterface / FHIR API. I tried to figure out the problem myself by modifying the logback.xml file so far that a complete log with all events is generated. A copy of this log-file is attached to this issue. It seems like there is an internal error when a resource is generated: "ca.uhn.fhir.rest.server.exceptions.InternalErrorException: HTTP 500 : Failed to call access method: java.lang.NullPointerException". Do you have a clue what the problem might be? 

Greetings from the Technical Unversity of Dresden, Germany!

[gt-fhir.log](https://github.com/gt-health/GT-FHIR2/files/2697855/gt-fhir.log)

**Comment by myungchoi** [comment]
Can you post the Patient resource that you are trying to post?

**Comment by ckamann** [comment]
I used the Patient example from the FHIR documentation:

`<Patient xmlns="http://hl7.org/fhir">
  <id value="example"/> 
  <text> 
    <status value="generated"/> 
    <div xmlns="http://www.w3.org/1999/xhtml">
      <table> 
        <tbody> 
          <tr> 
            <td> Name</td> 
            <td> Peter James 
              <b> Chalmers</b>  (&quot;Jim&quot;)
            </td> 
          </tr> 
          <tr> 
            <td> Address</td> 
            <td> 534 Erewhon, Pleasantville, Vic, 3999</td> 
          </tr> 
          <tr> 
            <td> Contacts</td> 
            <td> Home: unknown. Work: (03) 5555 6473</td> 
          </tr> 
          <tr> 
            <td> Id</td> 
            <td> MRN: 12345 (Acme Healthcare)</td> 
          </tr> 
        </tbody> 
      </table> 
    </div> 
  </text> 
  
  <identifier> 
    <use value="usual"/> 
    <type> 
      <coding> 
        <system value="http://hl7.org/fhir/v2/0203"/> 
        <code value="MR"/> 
      </coding> 
    </type> 
    <system value="urn:oid:1.2.36.146.595.217.0.1"/> 
    <value value="12345"/> 
    <period> 
      <start value="2001-05-06"/> 
    </period> 
    <assigner> 
      <display value="Acme Healthcare"/> 
    </assigner> 
  </identifier> 
  <active value="true"/> 
  
  <name> 
    <use value="official"/> 
    <family value="Chalmers"/> 
    <given value="Peter"/> 
    <given value="James"/> 
  </name> 
  <name> 
    <use value="usual"/> 
    <given value="Jim"/> 
  </name> 
  <name> 
    
    <use value="maiden"/> 
    <family value="Windsor"/> 
    <given value="Peter"/> 
    <given value="James"/> 
    <period> 
      <end value="2002"/> 
    </period> 
  </name> 
  <telecom> 
    <use value="home"/> 
    
  </telecom> 
  <telecom> 
    <system value="phone"/> 
    <value value="(03) 5555 6473"/> 
    <use value="work"/> 
    <rank value="1"/> 
  </telecom> 
  <telecom> 
    <system value="phone"/> 
    <value value="(03) 3410 5613"/> 
    <use value="mobile"/> 
    <rank value="2"/> 
  </telecom> 
  <telecom> 
    <system value="phone"/> 
    <value value="(03) 5555 8834"/> 
    <use value="old"/> 
    <period> 
      <end value="2014"/> 
    </period> 
  </telecom> 
  
  <gender value="male"/> 
  <birthDate value="1974-12-25">
    <extension url="http://hl7.org/fhir/StructureDefinition/patient-birthTime">
      <valueDateTime value="1974-12-25T14:35:45-05:00"/> 
    </extension> 
  </birthDate> 
  <deceasedBoolean value="false"/> 
  <address> 
    <use value="home"/> 
    <type value="both"/> 
    <text value="534 Erewhon St PeasantVille, Rainbow, Vic  3999"/> 
    <line value="534 Erewhon St"/> 
    <city value="PleasantVille"/> 
    <district value="Rainbow"/> 
    <state value="Vic"/> 
    <postalCode value="3999"/> 
    <period> 
      <start value="1974-12-25"/> 
    </period> 
  </address> 
  <contact> 
    <relationship> 
      <coding> 
        <system value="http://hl7.org/fhir/v2/0131"/> 
        <code value="N"/> 
      </coding> 
    </relationship> 
    <name> 
      <family value="du Marché">
        
        <extension url="http://hl7.org/fhir/StructureDefinition/humanname-own-prefix">
          <valueString value="VV"/> 
        </extension> 
      </family> 
      <given value="Bénédicte"/> 
    </name> 
    <telecom> 
      <system value="phone"/> 
      <value value="+33 (237) 998327"/> 
    </telecom> 
    <address> 
      <use value="home"/> 
      <type value="both"/> 
      <line value="534 Erewhon St"/> 
      <city value="PleasantVille"/> 
      <district value="Rainbow"/> 
      <state value="Vic"/> 
      <postalCode value="3999"/> 
      <period> 
        <start value="1974-12-25"/> 
      </period> 
    </address> 
    <gender value="female"/> 
    <period> 
      
      <start value="2012"/> 
    </period> 
  </contact> 
  <managingOrganization> 
    <reference value="Organization/1"/> 
  </managingOrganization> 
</Patient> `

I also simplified it so that there was only an identifyer, a name and an address. Also other example resources didn't work like Organization or Observation. So the error appears to be indepent from the posted resource.

**Comment by myungchoi** [comment]
I can't see the actual raw Patient resource. I think Github's markup viewer is trying to parse this.

**Comment by ckamann** [comment]
I added the link to the resource.

**Comment by myungchoi** [comment]
One of telecom had no system info, which caused the null exception. I updated my local copy to handle this. I have other updates that I am working on. I will need to finish them to update the repo. Until then, you can just add system to those that do not have system in telecom section.

And, I also found that it fails for adding location (address). You will need to change it to fit in US address system. For example, state must be 2 characters. 

Please try with these changes to the Patient resource. 

And, text can be removed as we only use structure data. And, please remove id from the resource as we are creating. 

Please update us here how things go.

**Comment by myungchoi** [comment]
Some of issues have been fixed for Patient create. I verified creating Patient with US address successful. Please update your repository and reopen this issue if you still have a problem with latest updates.
