### ISSUE TITLE
OMOP to STU3 Mapping

### ISSUE THREAD

**Issue by sohrabhejazi** [gt-health/GT-FHIR2#69]
There is only [OMOP to USTU2 Mappings](https://github.com/gt-health/GT-FHIR2/blob/master/docs/fhir_omop_mapping.md) in your repository. I have not found any document to map OMOP to STU3. Could you please send it to me? 
It would be very useful for our research.

**Comment by myungchoi** [comment]
We haven't generated the mapping document yet. We have spreadsheet but they are not complete. We have more mapping done on the coding.  Please see if you can open this link.

https://docs.google.com/spreadsheets/d/11ZmwGxnXViLkTVdX5Vi0FP-Gh4AD2HZEfYOhzZptZfw/edit#gid=1212761421

**Comment by sohrabhejazi** [comment]
Thank you very much.
