### ISSUE TITLE
https instead of http

### ISSUE THREAD

**Issue by sohrabhejazi** [gt-health/GT-FHIR2#70]
Hi,

The base URL of the server is HTTP. I need an HTTPS instead because the browsers block active mixed content by default.
Could you make the base URL available via HTTPS?

LG,
Sohrab

**Comment by myungchoi** [comment]
Hi, Sohrab,

The server app is running on Tomcat server. So, you need to set up the HTTPS on Tomcat configuration file. Here is general info on ssl configuration.

https://tomcat.apache.org/tomcat-8.0-doc/ssl-howto.html

If you are using docker container, the follow will help on setting ssl on tomcat in the docker container.

https://qmetrysupport.atlassian.net/wiki/spaces/QTMS844/pages/888373261/SSL+Certificate+Configuration+for+Tomcat+in+Docker

Or, if you have proxy server, you can set up https on the proxy server and use http between proxy and local OMOPonFHIR server. 

Please let me know if you have any question. Please remember that if you use self-signed, many browsers/clients will reject the connection.

**Comment by sohrabhejazi** [comment]
Many thanks.
